USE [master]
GO

/****** Object:  Database [HermesAuth]    Script Date: 5/6/2016 12:56:09 PM ******/
DROP DATABASE [HermesAuth]
GO

/****** Object:  Database [HermesAuth]    Script Date: 5/6/2016 12:56:09 PM ******/
CREATE DATABASE [HermesAuth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HermesAuth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HermesAuth.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HermesAuth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HermesAuth_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HermesAuth] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HermesAuth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HermesAuth] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HermesAuth] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HermesAuth] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HermesAuth] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HermesAuth] SET ARITHABORT OFF 
GO

ALTER DATABASE [HermesAuth] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HermesAuth] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HermesAuth] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HermesAuth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HermesAuth] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HermesAuth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HermesAuth] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HermesAuth] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HermesAuth] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HermesAuth] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HermesAuth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HermesAuth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HermesAuth] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HermesAuth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HermesAuth] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HermesAuth] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HermesAuth] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HermesAuth] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HermesAuth] SET  MULTI_USER 
GO

ALTER DATABASE [HermesAuth] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HermesAuth] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HermesAuth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HermesAuth] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HermesAuth] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HermesAuth] SET  READ_WRITE 
GO


